### ISSUE TITLE
TypeError: Invalid input type 'PdfDocument'

### ISSUE THREAD

**Issue by tosolveit** [tensorlakeai/indexify-extractors#174]
---

### **Bug Report: `indexify-extractor` Command Fails Due to `pypdfium2` Library Issue**

**Description:**
When attempting to run the `indexify-extractor download` command, an error occurs related to the `pypdfium2` library. The command fails with a `TypeError` indicating an invalid input type.

**Command:**
```
indexify-extractor download hub://pdf/marker
```

**Error Traceback:**
```
Traceback (most recent call last):
  ...
  File "/path/to/pypdfium2/_helpers/document.py", line 674, in _open_pdf
    raise TypeError(f"Invalid input type '{type(input_data).__name__}'")
TypeError: Invalid input type 'PdfDocument'
-> Cannot close object, library is destroyed. This may cause a memory leak!
```

**Steps to Reproduce:**
1. Install the `indexify-extractor` and `pypdfium2` libraries.
2. Run the command `indexify-extractor download hub://pdf/marker`.
3. Observe the error traceback.

**Expected Behavior:**
The command should execute successfully, downloading the specified extractor without errors.

**Environment:**
- OS: MAC OS 14.4.1
- Python version: 3.10.5
- Indexify-extractor version: 0.0.66
- pypdfium2 version: 4.30
---

**Comment by diptanu** [comment]
This was fixed by updating marker
